In [1]:
import numpy as np
import torch
import torch.nn as nn

***
***
# Min and Max using NumPy
#### **numpy has built in functions to calculate the following**:
1. **minimum** - smallest / least number in a set
2. **maximum** - largest / greatest number in a set
3. **minimum index** - position of smallest number in a set 
4. **maximum index** - position of largest number in a set
- *note*: for the indexes they return the index position of a value in a set, not the actual value
- *additional note*: the argmin and argmax will count starting at 0, not 1

In [3]:
# example 1

# finding minimum and maximum from a set of numbers
vector = np.array([-2,60,7,-15])

min_val = np.min(vector)
max_val = np.max(vector)

print("min value: %g, max value: %g"%(min_val,max_val))

# finding positions of min and max
min_idx = np.argmin(vector)
max_idx = np.argmax(vector)

print("position of minimum: %g, position of maximum: %g" %(min_idx,max_idx))

min value: -15, max value: 60
position of minimum: 3, position of maximum: 1


***
## Finding min / max with matrices
- biggest difference between this and an array is that you can find the max / min of the entire matrix, of each row, or of each of the columns 

In [12]:
# example 2

# matrix
m = np.array([
    [52, -1, 1],
    [6, 18, 5]
    ])
print(m,"\n")

# minimum values
min_all = np.min(m) # min for whole matrix
min_cols = np.min(m,axis = 0) # min for each column (across rows)
min_rows = np.min(m, axis = 1) # min for each row (across columns)

print("min of entire matrix:", min_all, "\nmin of columns:", min_cols,"\nmin of rows:",min_rows,"\n")

# positions of minimum values

min_all_idx = np.argmin(m)
min_cols_idx = np.argmin(m, axis = 0) # will return col index for each min, 0 starting at the top
min_rows_idx = np.argmin(m, axis = 1) # will return row index for each min, 0 starting at the left

print("index of min:", min_all_idx, "\nposition min of columns:", min_cols_idx,"\nposition min of rows:", min_rows_idx,"\n")

[[52 -1  1]
 [ 6 18  5]] 

min of entire matrix: -1 
min of columns: [ 6 -1  1] 
min of rows: [-1  5] 

index of min: 1 
position min of columns: [1 0 0] 
position min of rows: [1 2] 



***
***
# Using PyTorch
- almost identical to numpy, all of the functions have the same names
- only big difference is the syntax
    - torch.function instead of np.function
- uses tensor data type

In [19]:
# example 3
vec = torch.tensor([-2,60,7,-15])

# finding min and max
torch_min = torch.min(vec)
torch_max = torch.max(vec)

print("minimum: %g, maximum: %g"%(torch_min, torch_max))

# finding positions of min and max
t_min_idx = torch.argmin(vec)
t_max_idx = torch.argmax(vec)

print("position of minimum: %g, position of maximum: %g" %(t_min_idx,t_max_idx))


minimum: -15, maximum: 60
position of minimum: 3, position of maximum: 1


***
## Brief example of matrix
- a nice addition to the min and max functions is that they also have the functionality of argmin and argmax.<br><br>
- Both values and indices are stored in an object.
    - can use dot operator to access values or indices <br><br>


In [23]:
# example 4

# matrix
m = torch.tensor([
    [52, -1, 1],
    [6, 18, 5]
    ])
print(m,"\n")

# minimum values, will return an object that contains min values and index positions
min_all = torch.min(m)
min_cols = torch.min(m,axis = 0) 
min_rows = torch.min(m, axis = 1)

print("min of entire matrix:", min_all, "\nmin of columns:", min_cols.values,"\nmin of rows:",min_rows.values,"\n")

# positions of minimum values

min_all_idx = torch.argmin(m)

print("index of min:", min_all_idx, "\nposition min of columns:", min_cols.indices,"\nposition min of rows:", min_rows.indices,"\n")

tensor([[52, -1,  1],
        [ 6, 18,  5]]) 

min of entire matrix: tensor(-1) 
min of columns: tensor([ 6, -1,  1]) 
min of rows: tensor([-1,  5]) 

index of min: tensor(1) 
position min of columns: tensor([1, 0, 0]) 
position min of rows: tensor([1, 2]) 

