# Dropout Regularization!
#### What is it?
- **Dropout regularization** is an effective method to improve the performance and generalizability of deep learning models.
- During each training epoch, individual nodes / units in model layers randomly have their activation set to zero.
- These nodes are **not** actually removed from the model.
- This should *not be applied* during model evaluation.

#### Why is it used?
- Dropout regularization aims to prevent units from learning too much individually, promotes distributed representations, and increases model stability
- Improves generalizability, reduces overfitting, improves testing accuracy.

In [1]:
import torch
import torch.nn as nn
import torch.nn.functional as F

In [10]:
# defining probability for a node to dropout
drop_prob = 0.25

dropout = nn.Dropout(p=drop_prob) # dropout layer
x = torch.ones(10)

# dropout results after passing through dropout layer
y = dropout(x)

# printing results
print(x)
print(y)
print(torch.mean(y))

tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])
tensor([1.3333, 0.0000, 1.3333, 0.0000, 1.3333, 1.3333, 1.3333, 1.3333, 1.3333,
        0.0000])
tensor(0.9333)


### Dropout when evaluating the Model

In [13]:
dropout.eval() # model now in evaluation mode, dropout is disabled
y = dropout(x)
print(y)
print(torch.mean(y))

tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])
tensor(1.)


### Important note about `F.droput()` .
- It does not de-active automatically when in eval() mode.
- This can be avoided by including in the params `training=False`.

In [17]:
dropout.eval() # model now in evaluation mode, dropout should be disabled

y = F.dropout(x) # calling the dropout function directly, so it is not disabled
print("Dropout still being applied in eval()")
print(y) # expected to be all ones
print(torch.mean(y)) # expected to be 1

# this can be fixed with included the training bool in the dropout function
y = F.dropout(x, training=False)

print("\nDropout not being applied in eval()")
print(y)
print(torch.mean(y))

Dropout still being applied in eval()
tensor([2., 2., 0., 2., 0., 0., 0., 2., 0., 0.])
tensor(0.8000)

Dropout not being applied in eval()
tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])
tensor(1.)


### Important note about switching model between training and eval modes.
- If the model is switched into `.eval()` mode, it will stay this way until it is manually set back into training. 
    - As long as this is enabled dropout will not be applied.
- A call to `.train()` must be included to set the model back into training mode.

In [18]:
# example of toggling model modes between training and evaluation

dropout.train() # model now in training mode
y = dropout(x)
print(f"Model in training mode: {y}\n")

dropout.eval() # model now in evaluation mode
y = dropout(x)
print(f"Model in evaluation mode: {y}\n")

# example of accidentally trying to train while still in eval mode
y = dropout(x)
print(f"Model in evaluation mode: {y}\n") # expected to be the same as the previous result

Model in training mode: tensor([1.3333, 1.3333, 1.3333, 1.3333, 0.0000, 1.3333, 1.3333, 1.3333, 1.3333,
        1.3333])

Model in evaluation mode: tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

Model in evaluation mode: tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

