In [1]:
import numpy as np
import torch

# Random numbers and seeding!
- ensures the **same set of random numbers can be reproduced**
- essential for sharing code 
- ensuring consistent results in deep learning models

## Seeding with NumPy

***
#### Creating a list of random numbers

In [2]:
# example 1 - making random numbers via random.randn function
np.random.randn(5)

array([-0.32314115, -1.35855552, -0.09148985, -1.47510295, -0.64391638])

***
#### Method to create a seed
- when a seed is fixed, the random values initially generated will be the same with each following rerun of the code.
- with the below method, it sets the seed for all of the random functions. It does not allow for instanced seeding.

In [11]:
# example 2 - seed creating with widely used method

# fix the seed, acts globally
np.random.seed(7)

print(np.random.randn(8))
print(np.random.randn(19))


[ 1.69052570e+00 -4.65937371e-01  3.28201637e-02  4.07516283e-01
 -7.88923029e-01  2.06557291e-03 -8.90385858e-04 -1.75472431e+00]
[ 1.01765801  0.60049852 -0.62542897 -0.17154826  0.50529937 -0.26135642
 -0.24274908 -1.45324141  0.55458031  0.12388091  0.27445992 -1.52652453
  1.65069969  0.15433554 -0.38713994  2.02907222 -0.04538603 -1.4506787
 -0.40522786]


***
#### Alternate seed creation method
- creating seeds with the *RandomState* method!
    - creates an object where the " . " operator can be used to access the .randn function in numpy.
- not necessarily better, but it is newer, more flexible, and generally recommended.
- can create and use multiple seeds in the same program

In [22]:
# example 3) local seeds

rand_seed_1 = np.random.RandomState(31)
rand_seed_2 = np.random.RandomState(44)

print(rand_seed_1.randn(3)) # uses seed 1, does not change between runs
print(rand_seed_2.randn(3)) # uses seed 2, does not change between runs
print(rand_seed_1.randn(3)) # different, does not change between runs
print(rand_seed_2.randn(3)) # different, does not change between runs
print (np.random.randn(3)) # changes every run

[-0.41475721 -0.33336867  0.08109199]
[-0.75061472  1.31635732  1.24614003]
[-0.79102695 -0.21859967 -0.76319684]
[-1.60491574 -1.46814368 -1.71507046]
[ 0.50162412 -0.09477545  1.19308592]


***
***
## Seeding with PyTorch
- seeding with pytorch is similar to the method shown in example 2, where it is more of a global scope and would affect all random variables.

***
#### Creating random numbers:

In [23]:
torch.randn(5)

tensor([ 1.1497, -0.5807,  0.3513, -0.6467, -0.2579])

***
#### Creating a seed

- torch's *manual_seed* function is local to pytorch, and it does not affect anything with numpy

In [32]:
torch.manual_seed(5)
print(torch.randn(5)) # should be same every time

print(np.random.randn(5)) # should be different every time


tensor([-0.4868, -0.6038, -0.5581,  0.6675, -0.1974])
[ 0.6547057   0.8943523   0.41550261 -0.92354466 -0.19602731]
